// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutMediaOverlay from '@/components/sections/about/AboutMediaOverlay';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
        <SectionErrorBoundary name="about">
              <AboutMediaOverlay
          tag="Why Elevation Media ?"
          title="We Help Local Businesses Thrive"
          description="From medical practices to law firms, we understand the nuances that make a website work for local businesses. We don't just build sites—we help businesses establish credibility, attract more customers, and generate more leads."
          primaryButton={{
            text: "Work With Us",
            href: "#contact",
          }}
          imageSrc="http://img.b2bpic.net/free-photo/manager-who-keeps-track-sales-figures-phone-screen-moon-light_482257-32838.jpg"
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
