// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
        <SectionErrorBoundary name="contact">
              <ContactCta
          tag="Ready to Start?"
          text="Elevate your business today. Contact our team for a free consultation and let's discuss how we can help you grow."
          primaryButton={{
            text: "Schedule Consultation",
            href: "#ContactSection",
          }}
          secondaryButton={{
            text: "Email Us",
            href: "mailto:elevatedbuisnesses@gmail.com",
          }}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
