// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqTabbedAccordion from '@/components/sections/faq/FaqTabbedAccordion';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqTabbedAccordion
          tag="FAQ"
          title="Frequently Asked Questions"
          description="Common questions about how we help businesses grow."
          categories={[
            {
              name: "General",
              items: [
                {
                  question: "How long does a website take to build?",
                  answer: "Typically 1-3 weeks depending on project scope.",
                },
                {
                  question: "Do you handle maintenance?",
                  answer: "Yes, we offer ongoing maintenance and growth services.",
                },
              ],
            },
            {
              name: "Process",
              items: [
                {
                  question: "How do we get started?",
                  answer: "Schedule a discovery call to discuss your business goals.",
                },
                {
                  question: "What industries do you work with?",
                  answer: "We serve law firms, clinics, gyms, salons, and more.",
                },
              ],
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
