// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "features" section.

import React from 'react';
import FeaturesRevealCards from '@/components/sections/features/FeaturesRevealCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FeaturesSection(): React.JSX.Element {
  return (
    <div id="features" data-section="features">
        <SectionErrorBoundary name="features">
              <FeaturesRevealCards
          tag="Our Expertise"
          title="More Than Just A Pretty Website"
          description="We focus on real results. Our strategy-first approach ensures your site serves as a powerful engine for lead generation and business growth."
          items={[
            {
              title: "Mobile Responsive Design",
              description: "Ensure your business looks incredible on every screen, from iPhones to desktops.",
              imageSrc: "http://img.b2bpic.net/free-photo/structure-social-media-with-colored-icons_1134-73.jpg",
            },
            {
              title: "SEO Strategy & Growth",
              description: "Get found by customers searching for the exact services you provide.",
              imageSrc: "http://img.b2bpic.net/free-photo/arrange-white-letters-as-seo_1384-118.jpg",
            },
            {
              title: "High-Converting Funnels",
              description: "We turn visitors into leads with strategic layouts and clear calls to action.",
              imageSrc: "http://img.b2bpic.net/free-photo/filter-icon-front-side-with-white-background_187299-39851.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
