// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroSplit from '@/components/sections/hero/HeroSplit';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroSplit
          tag="Elevation Media"
          title="Establish Your Presence & Grow."
          description="We build high-converting, beautiful websites that turn visitors into loyal customers. Let Elevation Media take your online presence to new heights."
          primaryButton={{
            text: "Start Growing",
            href: "#contact",
          }}
          secondaryButton={{
            text: "Our Services",
            href: "#services",
          }}
          imageSrc="https://storage.googleapis.com/webild/users/user_3GTaMoXuYSTqX2LVBuutSAbAz5R/tmp/a-premium-abstract-futuristic-mountain-l-1783998630458-840bb021.png"
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
