// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "metrics" section.

import React from 'react';
import MetricsFeatureCards from '@/components/sections/metrics/MetricsFeatureCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MetricsSection(): React.JSX.Element {
  return (
    <div id="metrics" data-section="metrics">
        <SectionErrorBoundary name="metrics">
              <MetricsFeatureCards
          tag="Proven Results"
          title="Driving Real Business Impact"
          description="Our data-driven strategies produce consistent growth for our clients."
          metrics={[
            {
              value: "45%",
              title: "Average Increase in Leads",
              features: [
                "Optimized funnels",
                "Faster load speeds",
              ],
            },
            {
              value: "82%",
              title: "Improvement in SEO Ranking",
              features: [
                "Targeted local keywords",
                "Content authority",
              ],
            },
            {
              value: "3x",
              title: "Return on Web Investment",
              features: [
                "Higher conversion rates",
                "Reduced bounce rates",
              ],
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
