// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "services" section.

import React from 'react';
import FeaturesRevealCardsBento from '@/components/sections/features/FeaturesRevealCardsBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ServicesSection(): React.JSX.Element {
  return (
    <div id="services" data-section="services">
        <SectionErrorBoundary name="services">
              <FeaturesRevealCardsBento
          tag="Our Services"
          title="Comprehensive Web Solutions"
          description="Premium services designed to elevate your brand to the next level."
          items={[
            {
              title: "Website Design",
              description: "Beautiful, high-end UI design tailored to your specific brand.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/various-business-card-templates_23-2147725095.jpg",
            },
            {
              title: "SEO Consulting",
              description: "Rank higher on Google and outpace your local competition.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/top-view-pills-gridline_23-2148530902.jpg",
            },
            {
              title: "E-Commerce Setup",
              description: "Sell your products online with a modern, fast checkout experience.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/multiethnic-group-coworkers-analyzing-business-charts-infographics-data-laptop-software-people-doing-teamwork-collaboration-create-paper-reviews-professional-report-close-up_482257-48646.jpg",
            },
            {
              title: "Brand Identity",
              description: "Develop a cohesive look and feel that resonates with customers.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/communication-social-media-icons-personal-computer_23-2150781060.jpg",
            },
            {
              title: "Content Strategy",
              description: "Professional content that builds authority and converts visitors.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/top-view-delicious-food-arrangement_23-2149964955.jpg",
            },
            {
              title: "UX/UI Development",
              description: "Intuitive interfaces that make purchasing effortless for your customers.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/female-web-designer-office-with-notebook_23-2149749865.jpg",
            },
            {
              title: "Growth Analytics",
              description: "Understand your customers better with actionable performance data.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/high-angle-desk-concept-with-copy-space_23-2148459697.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
